blank_issues_enabled: true
contact_links:
  - name: Запросы функций
    url: https://github.com/kotrino/RuLRS-core/discussions/new
    about: Запросите новые функции в разделе идей обсуждения
  - name: Discord сообщество
    url: # TODO: добавьте вашу ссылку на Discord
    about: Задавайте и отвечайте на вопросы здесь
  - name: Веб-сайт
    url: # TODO: добавьте вашу ссылку на сайт
    about: Здесь вы найдете информацию о RuLRS
