#pragma once

#define RULRS4_TELEMETRY_SHIFT 2
#define RULRS4_TELEMETRY_BYTES_PER_CALL 5
#define RULRS4_TELEMETRY_MAX_PACKAGES (255 >> RULRS4_TELEMETRY_SHIFT)
#define RULRS8_TELEMETRY_BYTES_PER_CALL 10 // some of this is consumed by LinkStats buuuut....
#define RULRS8_TELEMETRY_SHIFT 3
#define RULRS8_TELEMETRY_MAX_PACKAGES (255 >> RULRS8_TELEMETRY_SHIFT)

#define RULRS4_MSP_BYTES_PER_CALL 5
#define RULRS8_MSP_BYTES_PER_CALL 10
#define RULRS_MSP_BUFFER 65
#define RULRS_MSP_MAX_PACKAGES ((RULRS_MSP_BUFFER/RULRS4_MSP_BYTES_PER_CALL)+1)

#define AP_MAX_BUF_LEN  64
