// Обеспечение обратной совместимости
#define RULRS_PROTOCOL_NAME RULRS_PROTOCOL_NAME
#define RULRS_PROTOCOL_VERSION RULRS_PROTOCOL_VERSION
#define RULRS_PACKET_SIZE RULRS_PACKET_SIZE
#define RULRS_MAX_PACKET_LENGTH RULRS_MAX_PACKET_LENGTH
// ... existing code ... 